# Generated by Django 4.2.11 on 2024-04-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name_plural": "3. Course"},
        ),
        migrations.AlterModelOptions(
            name="coursecategory",
            options={"verbose_name_plural": "2. Course Categories"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name_plural": "4. Student"},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={"verbose_name_plural": "1. Teacher"},
        ),
        migrations.AddField(
            model_name="course",
            name="featured_image",
            field=models.ImageField(null=True, upload_to="course_imgs"),
        ),
        migrations.AddField(
            model_name="course",
            name="techs",
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
