# Generated by Django 4.2.11 on 2024-04-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_course_options_alter_coursecategory_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="featured_image",
            new_name="featured_img",
        ),
    ]
