# Generated by Django 4.2.11 on 2024-04-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_course_featured_img_alter_course_techs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="featured_img",
            field=models.ImageField(null=True, upload_to="course_imgs"),
        ),
        migrations.AlterField(
            model_name="course",
            name="techs",
            field=models.TextField(),
        ),
    ]
