# Generated by Django 4.2.11 on 2024-04-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_student_options_alter_course_featured_img_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="remarks",
            field=models.TextField(),
        ),
    ]
