# Generated by Django 4.2.11 on 2024-04-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_chapter_remarks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="qualification",
            new_name="username",
        ),
    ]
