# Generated by Django 4.2.11 on 2024-05-12 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_studentcourseenrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="detail",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="skills",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_chapters",
                to="main.course",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_courses",
                to="main.teacher",
            ),
        ),
    ]
